modLoader="javafml"
loaderVersion="[38,)" (28 is current forge version)
license="BSD (3 clause)"
#issueTrackerURL="http://my.issue.tracker/"

[[mods]]
modId="stickyhands"
version="${file.jarVersion}"
displayName="Sticky Hands"
#updateJSONURL="http://myurl.me/"
description='''
A small client-only mod that prevents using the off-hand item automatically, if you run out of the main-hand item,
or using the main-hand item if you pick up something while using the off-hand.
'''
#displayURL="http://example.com/"
#logoFile="examplemod.png"
#credits="Thanks for this example mod goes to Java"
authors="gigaherz"

[[dependencies.stickyhands]]
    modId="forge"
    mandatory=true
    versionRange="[38.0.14,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.stickyhands]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"
