modLoader="javafml"
loaderVersion="[41,)"
license="BSD (3 clause)"

[[mods]]
modId="stickyhands"
version="${file.jarVersion}"
displayName="Sticky Hands"
description='''
A small client-only mod that prevents using the off-hand item automatically, if you run out of the main-hand item,
or using the main-hand item if you pick up something while using the off-hand.
'''
authors="gigaherz"

[[dependencies.stickyhands]]
    modId="forge"
    mandatory=true
    versionRange="[41.0.94,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.stickyhands]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
