
modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory (28 is current forge version)
#issueTrackerURL="http://my.issue.tracker/" #optional

[[mods]] #mandatory
modId="stickyhands" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Sticky Fingers" #mandatory
#updateJSONURL="http://myurl.me/" #optional
#displayURL="http://example.com/" #optional
#logoFile="examplemod.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
#authors="Love, Cheese and small house plants" #optional
description='''
A small client-only mod that prevents using the off-hand item automatically, if you run out of the main-hand item,
or using the main-hand item if you pick up something while using the off-hand.
'''

[[dependencies.stickyhands]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[28.1.0,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.stickyhands]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
